<script data-cfasync="false"
	src="../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
<script src="vendor/global/global.min.js"></script>
<script src="vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
<script src="vendor/chart.js/Chart.bundle.min.js"></script>
<script src="vendor/peity/jquery.peity.min.js"></script>
<script src="vendor/apexchart/apexchart.js"></script>
<script src="js/dashboard/dashboard-1.js"></script>
<script src="vendor/owl-carousel/owl.carousel.js"></script>
<script src="js/custom.min.js"></script>
<script src="js/deznav-init.js"></script>
<script src="js/demo.js"></script>
<script src="js/styleSwitcher.js"></script>
<script src="js/html2pdf.js"></script>
<script src="vendor/datatables/js/jquery.dataTables.min.js"></script>
<script src="js/plugins-init/datatables.init.js"></script>
<script src="js/custom.min.js"></script>
